services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: composer install && php artisan key:generate && php artisan migrate --force && php artisan db:seed --force
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        fromDatabase: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase: true
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase: true
      - key: DB_USERNAME
        fromDatabase: true
      - key: DB_PASSWORD
        fromDatabase: true

databases:
  - name: laravel-db
    plan: free
    mysqlVersion: 8
    envVars:
      - key: DATABASE_URL
        fromDatabase: true